/* Every product image in each brand's public/images/<folder>/, with the hero
   default first. Shared by the hero card stack (HeroProductCards) and the
   homepage "Represented brands" cards (AutoRotateImage), so the filename lists
   live in exactly one place. */

const FARRIS_NAMES = [
  "pilot-operated",
  "actuated-control-valve",
  "body-options",
  "compact-relief-valve",
  "cross-section-detail",
  "cross-section",
  "direct-spring-closeup",
  "direct-spring-flanged-lever",
  "direct-spring-lever",
  "direct-spring-valve",
  "insure-monitoring-compact",
  "insure-monitoring",
  "pilot-assisted-pair",
  "pilot-operated-branded",
  "pilot-operated-dual-gauge",
  "spring-operated-angle",
  "spring-operated-compact",
  "spring-operated-lever",
  "valve-pair",
  "valve-range-grouped",
  "valve-range",
];
const FARRIS = FARRIS_NAMES.map((n) => `/images/farris/${n}.jpg`);

const DYNAFLO_NAMES = [
  "df400-rotary-plug",
  "4000-pressure-controller",
  "5000-level-controller",
  "760-positioner",
  "dfc-dfo-actuators",
  "dflp-piston-actuator",
  "dfn-yokeless-actuator",
  "dfr-rotary-actuator",
  "dfrp-piston-actuator",
  "integral-valve-actuator",
  "pro-50-regulator",
  "ps2-positioner",
  "rotary-ball",
  "sliding-stem",
  "t950xp-transducer",
];
const DYNAFLO = DYNAFLO_NAMES.map((n) => `/images/dynaflo/${n}.jpg`);

const EST_NAMES = [
  "griptight-max",
  "air-cooled-hx",
  "cpi-perma-plug",
  "double-block-bleed",
  "g250-vacuum-tube-tester",
  "g650-vacuum-joint-tester",
  "griptight-elbow",
  "griptight-isolation",
  "griptight-pe",
  "griptight-reverse-pressure",
  "high-lift-flange-weld",
  "hydra-loc-sleeving",
  "manual-installation-tool",
  "od-griptight",
  "p2-plug",
  "ram-package",
  "removal-tool",
  "smart-ram-640t",
  "smart-ram-plus",
  "socket-weld-sqs",
  "tube-stabilizer",
];
const EST = EST_NAMES.map((n) => `/images/est/${n}.jpg`);

/** Keyed by the public/images/ folder name. */
export const brandProductImages: Record<string, string[]> = {
  farris: FARRIS,
  dynaflo: DYNAFLO,
  est: EST,
};

/** Brand slug (from lib/data.ts) → its public/images/ folder name. */
export const brandSlugToFolder: Record<string, string> = {
  "farris-engineering": "farris",
  "dyna-flo": "dynaflo",
  est: "est",
};

/* Homepage brand-card tiles — normalized derivatives of the shots above,
   generated by scripts/normalize-brand-cards.mjs into public/images/cards/:
   branded footer cropped, white margins trimmed, product re-centered at a
   uniform relative size on an identical 15:16 white canvas. Frames that can't
   sit cleanly on white (photographs, technical drawings) are left out here so
   every rotation frame gets the exact same treatment; the clean lead cut-out
   (from images/home/bestseller-*.jpg) always comes first. */
const CARD_EXCLUDE: Record<string, string[]> = {
  farris: [
    "pilot-operated", // photograph on a wooden pallet
    "actuated-control-valve", // photograph on grey
    "cross-section", // technical drawing
    "cross-section-detail", // technical drawing
  ],
  dynaflo: [],
  est: [
    "air-cooled-hx", // site photograph
    "hydra-loc-sleeving", // full-bleed illustration
  ],
};

const cardTiles = (folder: string, names: string[]) => [
  `/images/cards/${folder}/lead.jpg`,
  ...names
    .filter((n) => !CARD_EXCLUDE[folder].includes(n))
    .map((n) => `/images/cards/${folder}/${n}.jpg`),
];

/** Keyed by the public/images/ folder name. */
export const brandCardImages: Record<string, string[]> = {
  farris: cardTiles("farris", FARRIS_NAMES),
  dynaflo: cardTiles("dynaflo", DYNAFLO_NAMES),
  est: cardTiles("est", EST_NAMES),
};
